name: build-win

on: [push]

jobs:
  compile-for-windows:
    runs-on: ubuntu-latest
    steps:
     - name: Set up Python
       uses: actions/setup-python@v3

     - name: Install SCons
       run: |
         pip install scons

     - name: Set up MinGW
       uses: egor-tensin/setup-mingw@v2
       with:
         platform: x64

     - name: clone repository and submodules
       run: git clone https://github.com/zodywoolsey/gdopus --recurse-submodules

     - name: build opus static library with -fPIC
       run: |
        cd gdopus/src/opus
        mkdir build-win
        cd build-win
        cmake -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DCMAKE_MSVC_RUNTIME_LIBRARY="MultiThreaded" -DCMAKE_C_COMPILER=x86_64-w64-mingw32-gcc -DCMAKE_CXX_COMPILER=x86_64-w64-mingw32-g++ ..
        cmake --build . --config Release
        ls

     - name: compile extension with scons
       run: |
        cd gdopus/
        scons platform=Windows
     - uses: actions/upload-artifact@v4
       with:
         name: windows build files
         path: gdopus/gdextensiontest/bin/
         overwrite: true
     - run: echo "finished, artifacts should be named 'extension files'"
