name: build-linux

on: [push]

jobs:
  runMultipleCommands:
    runs-on: ubuntu-latest
    steps:
     - run: git checkout https://github.com/zodywoolsey/gdopus --recurse-submodules
     - run: ls src/opus
     - run: |
        cd src/opus
        mkdir build
        cd build
        cmake ..
        cmake --build .
     - run: echo "finished"
