name: build-linux

on: [push]

jobs:
  runMultipleCommands:
    runs-on: ubuntu-latest
    steps:
     - name: Set up Python
       uses: actions/setup-python@v3

     - name: Install SCons
       run: |
         pip install scons

     - run: git clone https://github.com/zodywoolsey/gdopus --recurse-submodules
     - run: ls
     - run: |
        cd gdopus/src/opus
        mkdir build
        cd build
        cmake -DCMAKE_POSITION_INDEPENDENT_CODE=ON ..
        cmake --build .
        cd ../../..
        scons
     - run: echo "finished"
