name: build-linux

on: [push]

jobs:
  runMultipleCommands:
    runs-on: ubuntu-latest
    steps:
     - name: Set up Python
       uses: actions/setup-python@v3

     - name: Install SCons
       run: |
         pip install scons

     - name: clone repository and submodules
       run: git clone https://github.com/zodywoolsey/gdopus --recurse-submodules

     - name: build opus static library with -fPIC
       run: |
        cd gdopus/src/opus
        mkdir build
        cd build
        cmake -DCMAKE_POSITION_INDEPENDENT_CODE=ON ..
        cmake --build .

     - name: compile extension with scons
       run: |
        cd gdopus/
        scons
     - run: echo "finished"
