name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: cmake opus
    - run: cd src/opus
    - run: mkdir build
    - run: cd build
    - run: cmake ..
    - run: cmake --build .
