name: build-linux

on: [push]

jobs:
  runMultipleCommands:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v1
     - run: |
        ls src/opus
        cd src/opus
        mkdir build
        cd build
        cmake ..
        cmake --build .
     - run: echo "finished"
