name: build-linux

on: [push]

jobs:
  runMultipleCommands:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v1
     - run: |
        cd src/opus
        mkdir build
        ls
        cd build
        ls
        cmake ..
        ls
        cmake --build .
        ls
     - run: echo "finished"
